#!/bin/bash

# Git Helper Functions
# Handles git operations for automatic commits after successful tests

# Initialize git repository if needed
git_init_if_needed() {
    local project_dir=$1
    
    if [ ! -d "$project_dir/.git" ]; then
        echo "📦 Initializing git repository..."
        cd "$project_dir" || return 1
        git init || {
            echo "❌ Failed to initialize git repository"
            return 1
        }
        echo "✓ Git repository initialized"
    fi
    
    return 0
}

# Configure git user if provided
git_configure_user() {
    local project_dir=$1
    local user_name=$2
    local user_email=$3

    cd "$project_dir" || return 1

    # Set provided values or use defaults if empty
    if [ -n "$user_name" ]; then
        git config user.name "$user_name" || {
            echo "⚠️  Warning: Failed to set git user.name"
        }
    else
        # Check if git has a global user.name
        if ! git config --global user.name >/dev/null 2>&1; then
            echo "⚠️  Warning: No git user.name configured globally or provided"
            echo "   Setting default: 'AI Agent Orchestrator'"
            git config user.name "AI Agent Orchestrator"
        fi
    fi

    if [ -n "$user_email" ]; then
        git config user.email "$user_email" || {
            echo "⚠️  Warning: Failed to set git user.email"
        }
    else
        # Check if git has a global user.email
        if ! git config --global user.email >/dev/null 2>&1; then
            echo "⚠️  Warning: No git user.email configured globally or provided"
            echo "   Setting default: 'ai-agent@workflow.local'"
            git config user.email "ai-agent@workflow.local"
        fi
    fi

    # Verify configuration
    local configured_name=$(git config user.name)
    local configured_email=$(git config user.email)
    echo "✓ Git user configured: $configured_name <$configured_email>"

    return 0
}

# Add remote if not exists
git_add_remote() {
    local project_dir=$1
    local remote_url=$2
    local remote_name=${3:-origin}

    cd "$project_dir" || return 1

    # Check if remote already exists
    if git remote get-url "$remote_name" &>/dev/null; then
        local current_url=$(git remote get-url "$remote_name")

        # Check if the URL is different (normalize for comparison)
        # Remove token from both URLs for comparison
        local current_url_normalized=$(echo "$current_url" | sed 's|https://[^@]*@|https://|')
        local new_url_normalized=$(echo "$remote_url" | sed 's|https://[^@]*@|https://|')

        if [ "$current_url_normalized" = "$new_url_normalized" ]; then
            echo "✓ Remote '$remote_name' already configured with correct URL"
            return 0
        else
            echo "⚠️  Remote '$remote_name' exists but with different URL"
            echo "   Current: $current_url_normalized"
            echo "   Expected: $new_url_normalized"
            echo "📡 Updating remote URL..."
            git remote set-url "$remote_name" "$remote_url" || {
                echo "❌ Failed to update remote URL"
                return 1
            }
            echo "✓ Remote URL updated"
            return 0
        fi
    fi

    echo "📡 Adding remote repository..."
    git remote add "$remote_name" "$remote_url" || {
        echo "❌ Failed to add remote repository"
        return 1
    }

    echo "✓ Remote added: $(echo "$remote_url" | sed 's|https://[^@]*@|https://***@|')"
    return 0
}

# Commit all changes
git_commit_changes() {
    local project_dir=$1
    local commit_message=$2
    local task_id=$3

    cd "$project_dir" || return 1

    echo "📝 Committing changes..."

    # Stage all changes (including untracked files)
    git add -A || {
        echo "❌ Failed to stage changes"
        return 1
    }

    # Check if there are changes to commit (after staging)
    if git diff --staged --quiet; then
        echo "ℹ️  No changes to commit"
        return 0
    fi

    # Create commit
    git commit -m "$commit_message" -m "Task ID: $task_id" -m "Auto-generated by AI Agent workflow" || {
        echo "❌ Failed to create commit"
        return 1
    }

    echo "✓ Changes committed"
    return 0
}

# Push to remote
git_push_changes() {
    local project_dir=$1
    local branch=$2
    local remote_name=${3:-origin}

    cd "$project_dir" || return 1

    # Get the current branch name
    local current_branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)

    if [ -z "$current_branch" ]; then
        echo "❌ Failed to determine current branch"
        return 1
    fi

    echo "🚀 Pushing to remote ($remote_name/$branch)..."
    echo "   Current branch: $current_branch"

    # If current branch doesn't match target branch, rename it
    if [ "$current_branch" != "$branch" ]; then
        echo "   Renaming branch: $current_branch → $branch"
        if ! git branch -m "$current_branch" "$branch" 2>&1; then
            echo "❌ Failed to rename branch"
            return 1
        fi
        echo "✓ Branch renamed to $branch"
    fi

    # Try to push current branch to remote with the target branch name
    if git push "$remote_name" "HEAD:$branch" 2>&1; then
        echo "✓ Successfully pushed to $remote_name/$branch"
        # Set upstream tracking
        git branch --set-upstream-to="$remote_name/$branch" "$branch" 2>/dev/null
        return 0
    else
        # If push fails, try with --set-upstream
        echo "⏳ Setting upstream and pushing..."
        if git push --set-upstream "$remote_name" "$branch" 2>&1; then
            echo "✓ Successfully pushed to $remote_name/$branch"
            return 0
        else
            echo "❌ Failed to push changes"
            echo "💡 Tip: Ensure you have permissions and the remote repository exists"
            return 1
        fi
    fi
}

# Full commit and push workflow
git_commit_and_push() {
    local project_dir=$1
    local commit_msg_prefix=$2
    local task_title=$3
    local task_id=$4
    local remote_url=$5
    local branch=$6
    local user_name=$7
    local user_email=$8
    
    echo ""
    echo "════════════════════════════════════════════════════════════════════"
    echo "🔧 Git: Committing and Pushing Code"
    echo "════════════════════════════════════════════════════════════════════"
    echo ""
    
    # Initialize git if needed
    git_init_if_needed "$project_dir" || return 1
    
    # Configure user if provided
    if [ -n "$user_name" ] || [ -n "$user_email" ]; then
        git_configure_user "$project_dir" "$user_name" "$user_email"
    fi
    
    # Add remote if URL provided
    if [ -n "$remote_url" ]; then
        git_add_remote "$project_dir" "$remote_url" || return 1
    else
        echo "⚠️  Warning: No remote repository URL provided"
        echo "   Commits will be created locally but NOT pushed to GitHub"
        echo "   To enable push, use --github-repo parameter when running the workflow"
    fi
    
    # Create commit message
    local commit_message="${commit_msg_prefix} ${task_title}"
    
    # Commit changes
    git_commit_changes "$project_dir" "$commit_message" "$task_id" || return 1
    
    # Push if remote URL provided
    if [ -n "$remote_url" ]; then
        git_push_changes "$project_dir" "$branch" || return 1
    else
        echo ""
        echo "⚠️  Skipping push - no remote repository URL provided"
        echo "   Code is committed locally but NOT on GitHub"
        echo "   Add remote manually with: git remote add origin <URL>"
        echo "   Then push with: git push -u origin $branch"
    fi

    echo ""
    echo "✅ Git operations completed successfully"
    echo ""
    
    return 0
}
